import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingCart,UserRound,Heart,Menu,X,Plus,Trash2,Store,Smartphone,Shirt,Home,Car,Sparkles,Package,LogOut,MapPin,Phone,User,ShoppingBag,CheckCircle2,Lock,Mail,Eye,EyeOff,CreditCard,Wallet} from 'lucide-react';
import './styles.css';
import {api,saveApiSession,clearApiSession} from './api.js';

const demo=[
{id:1,title:'هاتف ذكي حديث',price:8900,category:'إلكترونيات',description:'هاتف ذكي عملي للاستخدام اليومي.',icon:Smartphone},
{id:2,title:'قميص Polo أنيق',price:650,category:'ملابس',description:'قميص Polo أنيق ومناسب للاستعمال اليومي.',icon:Shirt},
{id:3,title:'طقم عطور فاخر',price:3200,category:'عطور',description:'مجموعة عطور مميزة لمحبي الروائح الفاخرة.',icon:Sparkles},
{id:4,title:'أريكة منزلية عصرية',price:12500,category:'المنزل',description:'أريكة عصرية للمنزل.',icon:Home},
{id:5,title:'إكسسوارات سيارة',price:1400,category:'سيارات',description:'إكسسوارات مفيدة للسيارة.',icon:Car},
{id:6,title:'منتج إلكتروني مميز',price:4200,category:'إلكترونيات',description:'منتج إلكتروني عملي.',icon:Smartphone}
];
const icons={إلكترونيات:Smartphone,ملابس:Shirt,المنزل:Home,سيارات:Car,عطور:Sparkles};
const cats=[['الكل',Store],['إلكترونيات',Smartphone],['ملابس',Shirt],['المنزل',Home],['سيارات',Car],['عطور',Sparkles]];
const paymentMethods=[
{id:'cod',title:'الدفع عند الاستلام',subtitle:'ادفع عند وصول الطلب',icon:Wallet},
{id:'bankily',title:'Bankily',subtitle:'الدفع عبر Bankily',icon:CreditCard},
{id:'sedad',title:'Sedad',subtitle:'الدفع عبر Sedad',icon:CreditCard},
{id:'masrivi',title:'Masrivi',subtitle:'الدفع عبر Masrivi',icon:CreditCard}
];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};

function App(){
const[category,setCategory]=useState('الكل'),[query,setQuery]=useState(''),[products,setProducts]=useState([]),[cart,setCart]=useState(()=>read('bayaa-cart',[])),[fav,setFav]=useState(()=>read('bayaa-favorites',[])),[session,setSession]=useState(()=>read('bayaa-session',null)),[orders,setOrders]=useState([]),[sellerOrders,setSellerOrders]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[menu,setMenu]=useState(false),[panel,setPanel]=useState(null),[authMode,setAuthMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:'',role:'buyer'}),[showPass,setShowPass]=useState(false),[customer,setCustomer]=useState({name:'',phone:'',city:'نواكشوط',address:''}),[addForm,setAddForm]=useState({title:'',price:'',category:'إلكترونيات',description:''}),[paymentMethod,setPaymentMethod]=useState('cod');
const load=async()=>{setLoading(true);try{const r=await api.products({category:category==='الكل'?'':category,q:query});setProducts((r.products||[]).map(p=>({...p,id:String(p.id),price:Number(p.price),icon:icons[p.category]||Package,sellerId:p.seller_id})));setError('')}catch(e){setProducts([]);setError(e.message)}finally{setLoading(false)}};
useEffect(()=>{localStorage.setItem('bayaa-cart',JSON.stringify(cart))},[cart]);
useEffect(()=>{localStorage.setItem('bayaa-favorites',JSON.stringify(fav))},[fav]);
useEffect(()=>{if(session)api.me().catch(()=>{clearApiSession();setSession(null)})},[]);
useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[category,query]);
useEffect(()=>{if(session){api.myOrders().then(r=>setOrders(r.orders||[])).catch(()=>{});if(session.role==='seller')api.sellerOrders().then(r=>setSellerOrders(r.orders||[])).catch(()=>{})}},[session]);
const shown=useMemo(()=>products.length?products:demo.filter(p=>(category==='الكل'||p.category===category)&&p.title.toLowerCase().includes(query.trim().toLowerCase())),[products,category,query]);
const total=cart.reduce((s,p)=>s+Number(p.price),0);
const add=p=>setCart(c=>[...c,p]);
const remove=i=>setCart(c=>c.filter((_,x)=>x!==i));
const toggle=id=>setFav(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);
const authSubmit=async e=>{e.preventDefault();setError('');try{const r=authMode==='login'?await api.login({email:form.email,password:form.password}):await api.register(form);saveApiSession(r);setSession(r.user);setPanel(null);setForm({name:'',email:'',password:'',role:'buyer'})}catch(e){setError(e.message)}};
const createProduct=async e=>{e.preventDefault();setError('');try{const r=await api.createProduct({title:addForm.title,price:Number(addForm.price),category:addForm.category,description:addForm.description,imageUrl:''});const p={...r.product,id:String(r.product.id),price:Number(r.product.price),icon:icons[r.product.category]||Package,sellerId:r.product.seller_id};setProducts(x=>[p,...x]);setAddForm({title:'',price:'',category:'إلكترونيات',description:''})}catch(e){setError(e.message)}};
const placeOrder=async e=>{e.preventDefault();setError('');if(!cart.length)return;try{const r=await api.createOrder({customerName:customer.name||session.name,phone:customer.phone,city:customer.city,address:customer.address,items:cart,total,paymentMethod});setOrders(o=>[r.order,...o]);setCart([]);setPanel('success')}catch(e){setError(e.message)}};
const logout=()=>{clearApiSession();setSession(null);setOrders([]);setSellerOrders([]);setPanel(null)};
return <div className="app" dir="rtl">
<header className="header"><div className="container nav"><button className="icon mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><a className="logo" href="#home"><span>بياع</span><small>BAYAA</small></a><nav className={menu?'links open':'links'}><a href="#home">الرئيسية</a><a href="#products">المنتجات</a><a href="#sell">بع معنا</a><a href="#about">عن بياع</a></nav><div className="actions"><button className="icon" onClick={()=>setPanel(session?'account':'auth')}><UserRound/></button><button className="cart-btn" onClick={()=>setPanel('cart')}><ShoppingCart/><b>{cart.length}</b></button></div></div></header>
<main>
<section id="home" className="hero"><div className="container hero-inner"><div><div className="badge"><Sparkles size={16}/> سوق موريتانيا بين يديك</div><h1>اشترِ، بِع، <span>واربح مع بياع</span></h1><p>منصة سوق رقمية تجمع البائعين والمشترين في مكان واحد.</p><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج..."/></div><div className="hero-stats"><div><strong>سوق مفتوح</strong><small>منتجات متنوعة</small></div><div><strong>بائعون</strong><small>محليون</small></div><div><strong>24/7</strong><small>متاح</small></div></div></div><div className="hero-card"><div className="hero-circle"><ShoppingCart size={64}/></div><strong>كل ما تحتاجه</strong><span>في مكان واحد</span></div></div></section>
<section className="container category-wrap"><div className="section-head"><h2>تصفح الأقسام</h2><a href="#products">عرض الكل</a></div><div className="categories">{cats.map(([n,I])=><button key={n} className={category===n?'cat active':'cat'} onClick={()=>setCategory(n)}><I/><span>{n}</span></button>)}</div></section>
<section id="products" className="container products-section"><div className="section-head"><div><h2>المنتجات</h2><p>{loading?'جاري التحميل...':'منتجات متاحة الآن'}</p></div></div>{error&&<div className="empty">{error}</div>}<div className="grid">{shown.map(p=>{const I=p.icon||Package;return <article className="product" key={p.id} onClick={()=>setPanel({type:'details',product:p})}><button className={fav.includes(p.id)?'heart active':'heart'} onClick={e=>{e.stopPropagation();toggle(p.id)}}><Heart size={19} fill={fav.includes(p.id)?'currentColor':'none'}/></button><div className="product-image"><I size={55}/></div><div className="product-body"><small>{p.category}</small><h3>{p.title}</h3><div className="price">{Number(p.price).toLocaleString('ar-MR')} <span>MRU</span></div><button className="add" onClick={e=>{e.stopPropagation();add(p)}}><Plus size={18}/> أضف للسلة</button></div></article>})}</div></section>
<section id="sell" className="sell container"><div><span className="eyebrow">للبائعين</span><h2>لديك منتج؟ ابدأ البيع مع بياع</h2><p>أنشئ حساب بائع وأضف منتجاتك مباشرة إلى السوق.</p></div><button onClick={()=>session?.role==='seller'?setPanel('seller'):(setAuthMode('register'),setPanel('auth'))}>ابدأ البيع الآن</button></section>
</main><footer id="about"><div className="container footer-inner"><div className="logo"><span>بياع</span><small>BAYAA</small></div><p>© 2026 BAYAA — سوقك الرقمي في موريتانيا</p></div></footer>
{panel==='auth'&&<div className="overlay"><aside className="modal auth-modal"><button className="modal-close" onClick={()=>setPanel(null)}><X/></button><div className="modal-icon"><Lock/></div><h2>{authMode==='login'?'تسجيل الدخول':'إنشاء حساب'}</h2>{error&&<p>{error}</p>}<form className="form" onSubmit={authSubmit}>{authMode==='register'&&<label><User/> الاسم<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label><Mail/> البريد الإلكتروني<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><Lock/> كلمة المرور<div className="password-wrap"><input required type={showPass?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?<EyeOff/>:<Eye/>}</button></div></label>{authMode==='register'&&<div className="role-switch"><button type="button" className={form.role==='buyer'?'active':''} onClick={()=>setForm({...form,role:'buyer'})}>مشتري</button><button type="button" className={form.role==='seller'?'active':''} onClick={()=>setForm({...form,role:'seller'})}>بائع</button></div>}<button className="checkout">{authMode==='login'?'دخول':'إنشاء الحساب'}</button></form><button className="switch-auth" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'ليس لديك حساب؟ إنشاء حساب':'لديك حساب؟ تسجيل الدخول'}</button></aside></div>}
{panel==='account'&&session&&<div className="overlay"><aside className="modal account-modal"><button className="modal-close" onClick={()=>setPanel(null)}><X/></button><div className="account-avatar"><UserRound/></div><h2>{session.name}</h2><p>{session.email}</p><span className="eyebrow">{session.role==='seller'?'بائع':'مشتري'}</span>{session.role==='seller'&&<button className="checkout" onClick={()=>setPanel('seller')}>لوحة البائع</button>}<div className="account-orders"><div><strong>{orders.length}</strong><span>طلباتي</span></div><div><strong>{fav.length}</strong><span>المفضلة</span></div></div><button className="seller-logout" onClick={logout}><LogOut size={17}/> تسجيل الخروج</button></aside></div>}
{panel==='cart'&&<div className="overlay"><aside className="drawer"><div className="drawer-head"><h2>سلة المشتريات</h2><button onClick={()=>setPanel(null)}><X/></button></div>{!cart.length?<div className="empty"><ShoppingCart/><p>السلة فارغة</p></div>:<><div className="cart-list">{cart.map((p,i)=>{const I=p.icon||Package;return <div className="cart-item" key={`${p.id}-${i}`}><I/><div><strong>{p.title}</strong><span>{Number(p.price).toLocaleString('ar-MR')} MRU</span></div><button onClick={()=>remove(i)}><Trash2 size={18}/></button></div>})}</div><div className="total"><span>الإجمالي</span><strong>{total.toLocaleString('ar-MR')} MRU</strong></div><button className="checkout" onClick={()=>setPanel(session?'checkout':'auth')}>متابعة الطلب</button></>}</aside></div>}
{panel==='checkout'&&<div className="overlay"><aside className="modal checkout-modal"><button className="modal-close" onClick={()=>setPanel(null)}><X/></button><div className="modal-icon"><ShoppingBag/></div><h2>إتمام الطلب والدفع</h2><p>أدخل بيانات التوصيل واختر طريقة الدفع المناسبة.</p>{error&&<p>{error}</p>}<form className="form" onSubmit={placeOrder}><label><User/> الاسم<input required value={customer.name||session?.name||''} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label><Phone/> رقم الهاتف<input required value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label><MapPin/> المدينة<input required value={customer.city} onChange={e=>setCustomer({...customer,city:e.target.value})}/></label><label><MapPin/> العنوان<input required value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></label><div className="payment-section"><div className="payment-title"><CreditCard size={18}/> <strong>طريقة الدفع</strong></div><div className="payment-options">{paymentMethods.map(m=>{const I=m.icon;return <button type="button" key={m.id} className={paymentMethod===m.id?'payment-option active':'payment-option'} onClick={()=>setPaymentMethod(m.id)}><span className="payment-icon"><I size={20}/></span><span className="payment-copy"><strong>{m.title}</strong><small>{m.subtitle}</small></span><span className="payment-radio">{paymentMethod===m.id?'✓':''}</span></button>})}</div><div className="payment-help">الدفع الإلكتروني سيتم توصيله بمزود الدفع عند تفعيل مفاتيح الحساب في Railway. لا يتم إدخال أي رقم بطاقة داخل BAYAA.</div></div><div className="total"><span>الإجمالي</span><strong>{total.toLocaleString('ar-MR')} MRU</strong></div><button className="checkout" type="submit">{paymentMethod==='cod'?'تأكيد الطلب':'متابعة الدفع'}</button></form></aside></div>}
{panel==='success'&&<div className="overlay"><aside className="modal success"><CheckCircle2 size={70}/><h2>تم استلام طلبك</h2><p>تم حفظ الطلب في حسابك بنجاح.</p><button className="checkout" onClick={()=>setPanel(null)}>حسنًا</button></aside></div>}
{panel?.type==='details'&&<div className="overlay"><aside className="modal"><button className="modal-close" onClick={()=>setPanel(null)}><X/></button>{React.createElement(panel.product.icon||Package,{size:64})}<span className="eyebrow">{panel.product.category}</span><h2>{panel.product.title}</h2><p>{panel.product.description}</p><div className="price large">{Number(panel.product.price).toLocaleString('ar-MR')} <span>MRU</span></div><button className="checkout" onClick={()=>{add(panel.product);setPanel('cart')}}>أضف للسلة</button></aside></div>}
{panel==='seller'&&session?.role==='seller'&&<div className="overlay"><aside className="seller-panel"><div className="seller-head"><div><span className="eyebrow">BAYAA SELLER</span><h2>لوحة البائع</h2><p>{session.name}</p></div><button onClick={()=>setPanel(null)}><X/></button></div><div className="seller-content"><div className="seller-stats"><div><strong>{products.filter(p=>String(p.sellerId)===String(session.id)).length}</strong><span>منتجاتي</span></div><div><strong>{sellerOrders.length}</strong><span>الطلبات</span></div><div><strong>{sellerOrders.reduce((s,o)=>s+Number(o.total||0),0).toLocaleString('ar-MR')} MRU</strong><span>المبيعات</span></div></div><form className="seller-form form" onSubmit={createProduct}><h3>إضافة منتج</h3><label>اسم المنتج<input required value={addForm.title} onChange={e=>setAddForm({...addForm,title:e.target.value})}/></label><label>السعر<input required type="number" min="1" value={addForm.price} onChange={e=>setAddForm({...addForm,price:e.target.value})}/></label><label>القسم<select value={addForm.category} onChange={e=>setAddForm({...addForm,category:e.target.value})}>{cats.slice(1).map(([n])=><option key={n}>{n}</option>)}</select></label><label>الوصف<textarea rows="3" value={addForm.description} onChange={e=>setAddForm({...addForm,description:e.target.value})}/></label><button className="checkout"><Plus/> إضافة المنتج</button></form><div className="seller-products-list">{products.filter(p=>String(p.sellerId)===String(session.id)).map(p=><div className="seller-product-row" key={p.id}><Package/><div><strong>{p.title}</strong><span>{Number(p.price).toLocaleString('ar-MR')} MRU</span></div><button onClick={async()=>{try{await api.deleteProduct(p.id);setProducts(x=>x.filter(q=>q.id!==p.id))}catch(e){setError(e.message)}}}><Trash2/></button></div>)}</div></div></aside></div>}
</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
